src/openmmio.py

This should solve the issue when using forcebalance with openmm targets:
/forcebalance/openmmio.py", line 812, in update_simulation
forcefield.CustomGBGenerator, forcefield.GBSAOBCGenerator, forcefield.GBVIGenerator]
AttributeError: 'module' object has no attribute 'GBVIGenerator'

Fix a small error: forcefield.GBVIGenerator has been removed from openmm

---

setup.py

Networkx v2 has recently been published, and as a result, the fresh installations of ForceBalance attempt to grab the latest version of networkx which leads to this error:
```
G.nodes[n][name] = values
TypeError: unhashable type: 'dict'
```

Avoid installing networkx v2

---

src/molecule.py

This fix helps `forcebalance` find `dcdlib` when geomeTRIC is called from the command line.

look for dcdlib in local folder

---

src/forcefield.py
src/liquid.py
src/molecule.py

Original error "etree not defined" does not indicate the reason, that lxml module is not found. New warning and error messages added to suggest installing the lxml module to solve the problem.

More intuitive error message when lxml module is missing

---

src/molecule.py

For some reason, the line `from builtins import input` was missing at the top, leading to errors when users were asked to enter strings in Python 2.7. This should fix the issue.

Molecule builtins

---

src/forcefield.py

The previous forcefield.py would crash if we mixed XML and text parameter files in a single optimization if both files contained free parameters. This PR fixes the issue.

Mix xml txt

---

.travis.yml
src/abinitio.py
src/data/npt.py
src/data/npt_lipid.py
src/forcefield.py
src/hydration.py
src/legacy/abinitio.py
src/lipid.py
src/liquid.py
src/molecule.py
src/nifty.py
src/optimizer.py
src/quantity.py
tools/TagMol2.py

This PR gets rid of all calls to `np.matrix` in order to avoid pending deprecation warnings.

Remove calls to np.matrix

---

src/openmmio.py

Previously, OpenMM XML parameter lines such as the one below will cause an error in ForceBalance because the codes assumed these interactions were defined in terms of atom classes (not atom types) which led to incorrect parameter names.  The fixed version will attempt to parse parameter lines defined using either atom types or atom classes (but not mixing both).
```    <Bond k="310787.5199999999" length="0.0973" type1="ho" type2="oh" parameterize="length,k"/>
```

Parse OpenMM XML format with either atom type / class specification

---

src/data/rtarget.py
src/target.py

This PR improves the remote target output file handling.
Previously only selected files generated by the `rtarget.py` is sent back by work_queue, including 'objective.p', 'indicate.log', 'rtarget.out'.
However, when a target writes additional files, such as when `writelevel > 1` and Abinitio target writes out QM and MM energy comparisons, these files are lost when using remote.
This PR improves the behavior, that compresses all files in the remote worker's temp folder as `target_result.tar.bz2` and send back through work_queue, then decompress it on the host to put in the same location. This allows all output files of the remote target to be consistent with the local target.

improve remote target output file handling

---

src/optimizer.py

This could help avoid this error:
```
TypeError: Cannot cast ufunc add output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```

improve stability of hessian diagonalization

---

src/forcefield.py
src/openmmio.py
src/opt_geo_target.py
src/smirnoff_hack.py
src/smirnoffio.py

This PR mainly contains refactoring and improvements of the molecules `sminoffio.py` and `opt_geo_target.py`
For the `sminoffio.py`
1. The `smirnoff_analyze_parameter_coverage()` function now supports optgeo_target, which contains many molecules and engines. The analysis is done by aggregating all mol2 files into an OpenFF topology.
2. New keyword is added to the openff API, to fix errors in OpenFF toolkit about geometries that are "planar" have undefined stereo chemistry. Error handling is also added to print out information about the file.
```
OffMolecule.from_file(fnm, allow_undefined_stereo=True)
```
3. Performance of numerical gradient evaluations are greatly improved, by implementing `smirnoff_update_pgrads` in `AbInitio_SMIRNOFF` and `build_system_mval_masks` in …

major improvements for smirnoff and optgeo targets

---

src/forcefield.py
src/smirnoffio.py
studies/022_opt_geo_target/optimize.in
studies/022_opt_geo_target/optimize.out

1) This PR adds an improved representation of the parameters as a NetworkX graph in `ForceField.pTree`, allowing the connections between parameters to be easily identified.  
2) A new method `ForceField.get_mathid(pid)` was added to obtain all of the mathematical parameter IDs associated with a parameter name (including evaluated and repeated parameters).
3) These methods are used in `OptGeoTarget_SMIRNOFF.build_system_mval_masks` to ensure that each SMIRKS-based parameter (including evaluated and repeated parameters) is correctly mapped to all of its mathematical parameter IDs.
4) Some changes in the example calculation.

Improved force field parameter representation and SMIRKS-based masking

---

src/forcefield.py
src/optimizer.py
src/smirnoff_hack.py
src/smirnoffio.py
studies/022_opt_geo_target/optimize.out

This PR uses the OpenFF API to apply changes to parameters in the SMIRNOFF (and all OpenFF-style) force fields.  This should work with all parameter types, "free" as well as "evaluated" parameters, and all targets.
One "todo" is to identify which hacks in `smirnoff_hack.py` are no longer necessary; @yudongqiu might want to take a look. Also tagging @j-wags .

Use the OpenFF API for force field modification

---

src/parser.py
src/smirnoffio.py

The purpose of this PR is to improve the performance of the `smirnoffio. assign_openff_parameter()` function.
This function is introduced in recent PR #148. In theory, updating parameters the OpenFF ForceField object through the API should be faster, I found in my benchmark that it actually become a bit slower than the previous version that cached the ForceField initialization. (Still faster than the original version without cache).
The reason for the performance regression is that the `assign_openff_parameter()` function is called `n_param` times each time the ForceBalance forcefield is updated in `make()`, and numerical displacements require make() function to be called `2 x n_param` times. Therefore the total scaling of the time that the `assign_openff_parameter()` is called is `2 x …

improve assign_openff_parameter performance by caching parameter search

---

src/forcefield.py
src/openmmio.py
src/smirnoffio.py

This PR contains:
1. Previously the `normal_modes()` method in OpenMM Engine performs the mass-weight scaling on the eigenvectors of the mass-weighted hessian matrix. This is not consistent with the other engines because the mass-weight scaling of the eigenvectors is also done in the `process_vectors()` function in `Vibration` target. This PR will fix it by removing the step.
2. The `Vibration_SMIRNOFF` target is improved by `smirnoff_update_pgrads()` to skip the calculation of gradients on parameters not related to the molecule of the target.
3. The `smirnoff_update_pgrads()` is also improved in `AbInitio_SMIRNOFF` target, to correctly follow the relation of parameters defined in `parameter_eval` to find which parameter is related to the molecule of this target.

Improve normal_modes() for OpenMM/SMIRNOFF Engine and Vibration_SMIRNOFF

---

src/objective.py
src/openmmio.py
src/smirnoffio.py
src/torsion_profile.py

This PR contains several improvements related to SMIRNOFF fitting:
1. Add writing the `"EnergyCompare.txt"` file in the `TorsionProfile` target. This file adopts the same format as the `AbInitio` target and is very useful for analyzing the fitting results.
2. Improve the stability of the OpenMM engine `optimize()` function. This improvement solves two problems. a) When the `minimizeEnergy()` does not converge within the `maxIterations`, it will raise error and let the user know. b) Even if the `simulation.minimizeEnergy()` converged, I found that the energy could still go down when re-run the function. Now we try that 10 times and check if the energy "really converged" or not.
3. The `smirnoff_analyze_parameter_coverage()` function is re-written. Now it takes the target options dict, …

Recent Improvements related to SMIRNOFF fitting

---

devtools/conda-envs/test_env.yaml

Now that pymbar has removed the API-breaking change in version 3.0.5, we can unpin the version and hopefully all tests will run normally.

Unpin pymbar version

---

devtools/conda-envs/test_env.yaml

I added a channel to the `test_env.yaml` file that isn't actually used. This PR cleans that up so future maintainers don't get confused. 
This is ready to go, but there's not rush to merge this -- It's just cosmetic.

[WIP] Clean up messy dependencies I left in travis yml

---

src/evaluator_io.py

Fitting against properties which do not have uncertainties defined currently leads to an exception being raised.
This PR adds checks for these cases and simply sets the reported uncertainty to be nan when not present.

[Evaluator] Fix Exception Raised for Undefined Uncertainties

---

src/optimizer.py

The optimization loop currently looks like:
1) calculate obj,grad
2) check convergence(obj, grad, step)
3) take step
4) check failure(step) (this is where the unintended convergence failure occurs)
5) calculate obj,grad (next cycle)
Step (4) above involves checking two "failure criteria". One of these criteria is that the step size is below a very small threshold `Optimizer.lowerbound`. The intended purpose is to quit when the objective function is very rough and it is not productive to perform further gradient-based optimization. The reason why "check failure" is located after (3), and not after (2), is because we don't need to evaluate the objective function and gradient again to know whether a failure has occurred.
The current implementation caused some unintended behavior. In an …

Move crash criteria after convergence criteria in optimization code

---

setup.py

The check for NumPy/SciPy installs in `setup.py` prints out a helpful message for the user and exits (so that the rest of the install attempt does not proceed) but raises exit code 0 when it should probably raise 1. This may cause some issues downstream when these packages are not installed properly but this error is only printed to stdout or a logfile but doesn't stop a conda build from happening.
Just to demonstrate this, since it can't easily be added to CI (`echo $?` prints the exit status of the last command, which I just learned by working on this)
```shell
bash-3.2$ python -c "exit()"
bash-3.2$ echo $?
0
bash-3.2$ python -c "raise Exception"
Traceback (most recent call last):
File "<string>", line 1, in <module>
Exception
bash-3.2$ echo $?
1
```
And here's what it looks like to the …

Re-raise exception when NumPy/SciPy imports fail

---

src/smirnoff_hack.py

Many cached methods in `smirnoff_hack` were broken by the 0.7.0 OFF Toolkit release. This PR fixes the existing OpenFF ToolkitWrapper caching methods, and adds caching for other expensive RDKit/AmberTools/OETK ToolkitWrapper methods.
@leeping, since these changes will be reverse-incompatible, we might choose to document the OFFTK>=0.7.0 version requirement somewhere. Is there anywhere in the docs/build instructions that would fit?

Update for OFFTK 070 

---

src/forcefield.py

The PR switches to using a simple regex pattern which ignores text between [ ... ] brakets to split the list of `parameter_eval` statements. This allows eval statements which contain nested commas inside of the PRM quotes (e.g. which contain SMIRKS patterns which themselves contain commas) to be correctly split.
Closes #186

Fix Parsing of Parameter Eval Statements with Commas

---

src/vibration.py

In `vibration.py`, changed definition of `a` matrix for a correct normal mode rearrangement.

Correct a matrix for normal mode rearrangement

---

.github/workflows/ci.yml
src/openmmio.py

Resolves https://github.com/leeping/forcebalance/issues/209 .
The problem was that the `SMIRNOFF` class calls `OpenMM.create_simulation()`, and the recently added Drude feature was checking for `OpenMM.forcefield._forces`, which is something not possessed by `SMIRNOFF.forcefield`.  The issue is fixed by checking for the presence of Drude forces using `OpenMM.system.getForces()` instead.

Use OpenMM.System instead of OpenMM.Forcefield to check for Drude force

---

src/optimizer.py
src/parser.py

When fitting against a large number of targets the number of `micro` directories created in `output.tmp`, and the number of files they contain, can grow quite large. This is especially true when the full optimisation takes many iterations >=20 to converge, and each individual iteration can require ~20-40 micro iterations before selecting a step size.
This PR adds an option to delete these `micro` directories after they are finished with, thus reducing the total number of files produced by an optimization. By default they are retained to preserve previous behaviour.

Add option to delete micro outputs

---

src/evaluator_io.py
src/forcefield.py
src/recharge_io.py
src/smirnoffio.py

This PR ensures that SMIRNOFF plugins (e.g. custom parameter handlers and functional forms) are loaded by default.

Load SMIRNOFF plugins by default

---

src/smirnoff_hack.py

This PR updates the Smirnoff hack file to work with the newest toolkit release, introducing a new argument to the partial charge assignment methods that normalize the net charge.

Smirnoff Hack update

---

.github/workflows/ci.yml
src/data/md_ism_hfe.py
src/data/npt.py
src/data/npt_lipid.py
src/data/nvt.py
src/evaluator_io.py
src/molecule.py
src/openmmio.py
src/tests/files/XmlScript_out/TIP3G2w_out_ref.xml
src/tests/files/forcefield/TIP3G2w.xml
src/tests/test_engine.py
src/tests/test_openmmio.py
studies/018_improper_angle/targets/dimethylamine.2D-scan/make-labels.py

My changes in #237 made ForceBalance work with EITHER openmm >=7.6 OR <7.6. However, I didn't take into consideration builds with no openmm at all. Since openmmio is imported even in the absense of an installed openmm package, the imports need to allow parsing of the file regardless of whether openmm is installed.
Since there are many variables here ({hard vs. soft imports}, {openmm 7.5 vs. 7.6 vs. no openmm}, {tests vs. studies}...) we should be pretty thorough in our checks. I propose the following:

Update all simtk imports to also be forward-compatible with OpenMM >7.6, and keep soft imports soft

---

.github/workflows/ci.yml
src/smirnoff_hack.py

This is a simpler approach than #248, as @j-wags pointed out.

Cache generate_conformers with hash_molecule_args_and_kwargs approach

---

src/openmmio.py

A `CustomBondForce` is commonly used to implement scaled14 interactions excluded from a `CustomNonbondedForce` and can contain different global parameters, for example, the scale parameter to scale the interactions by. This PR also checks the custom bond force for global parameters when copying forces to a new openmm system. See this issue https://github.com/openforcefield/smirnoff-plugins/issues/36

Update global parameters in a `CustomBondForce`

---

src/evaluator_io.py
src/smirnoffio.py
studies/022_opt_geo_target/optimize.out
studies/023_torsion_relaxed/optimize.out
studies/024_openff_evaluator/output_ref/optimize.out
studies/025_openff_recharge/output_ref/optimize.out
studies/026_smirnoff_14_scale/optimize.out
studies/027_openff_hessian_target/optimize.out

the unit system of openff-evaluator 0.3.9 has been changed to openff-units based on pint. So this simple fix is necessary. 
Tested to work on openff-evaluator 0.4.1 / tutorial04
this PR fixes https://github.com/leeping/forcebalance/issues/276

fix: evaluator unit bug

---

.github/workflows/ci.yml
devtools/conda-envs/test_env.yaml
setup.py
src/smirnoff_hack.py
src/smirnoffio.py

ForceBalance has a [cache for the `ChemicalEnvironment.validate` method](https://github.com/leeping/forcebalance/blob/10b9280cab9735634d25a4f9c8b3e84cb13a6bb1/src/smirnoff_hack.py#L75C1-L84). This hasn't been used for a while (we stopped validating SMARTS a while ago and now just treat them as strings instead of ChemicalEnvironments), and we're finally dropping the ChemicalEnvironment class in the 0.14.0 OpenFF Toolkit release. It should suffice to simply remove the cache here. 
CI on GitHub seems to be broken, but I tested the changes locally and was able to run study 22 successfully.

Remove validate cache since the ChemicalEnvironment class is being dropped in OFFTK 0.14
